### ISSUE TITLE
Not working as designed.

### ISSUE THREAD

**Issue by mike4slund** [shrocky2/GarageWeb#3]
fixed, sorry

**Comment by shrocky2** [comment]
Hello! You typed the word GarageWeb incorrectly...you forgot the “e” in the word garage.

Hope everything works out and you enjoy the project after this little hiccup!
Steve-o

**Comment by mike4slund** [comment]
Yes. I realized that after I posted. 

How about using all 3 relays on the same webpage? Or more than just the one. Do you have a setup guide for that? 

I did have to go into the relay test and other files to edit which gpio pins to choose. My relay board is a bit different than yours.

**Comment by shrocky2** [comment]
I am currently finishing an new version of this program that allows for up to 3 garage doors. This new version is will include web setup, and allow for use with Siri on an iPhone or Apple Watch. Once uploaded, you'll be able to use the exact same hardware that this current version uses, just builds upon it with extra door sensors.

**Comment by mike4slund** [comment]
That's awesome! Keep me updated when I can install!

**Comment by rhubarbo** [comment]
> I am currently finishing an new version of this program that allows for up to 3 garage doors. This new version is will include web setup, and allow for use with Siri on an iPhone or Apple Watch. Once uploaded, you'll be able to use the exact same hardware that this current version uses, just builds upon it with extra door sensors.

Any update on this? I am hoping to roll this out in a three door configuration. Thanks!

**Comment by shrocky2** [comment]
My new mulitdoor setup is complete and live on GitHub and YouTube. You can use the same hardware setup as this project, just need to download the new code. Find the code here: https://github.com/shrocky2/SiriGarage || YouTube Video Instructions found here: https://youtu.be/wfsYFM-9Dns

**Comment by rhubarbo** [comment]
Woot! Thanks. 


On Jun 22, 2021, at 5:16 PM, Steve ***@***.*** ***@***.***> > wrote:


Closed #3.
