### ISSUE TITLE
After so many attempts lock them out or require same amount of sucessful log intimes like at least 2 to 3, like the app, nice interface

### ISSUE THREAD

**Issue by emg17** [shrocky2/GarageWeb#4]
Easy to secure a little better if wanted

**Comment by shrocky2** [comment]
My new mulitdoor setup with Siri support is complete and live on GitHub and YouTube. This new project allows for up to 3 doors and has added security to prevent bad passwords. After 5 bad passwords, the system shuts down until the pi is rebooted.

You can use the same hardware setup as this project, just need to download the new code. Find the code here: https://github.com/shrocky2/SiriGarage || YouTube Video Instructions found here: https://youtu.be/wfsYFM-9Dns
